// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from www/Shared/Definitions.ts.
// If you need to change this file, edit www/Shared/Definitions.ts and
// regenerate it.
// DO NOT EDIT THIS FILE DIRECTLY!!!

// Generated by guidiff v0.1.0

import * as TC from '@freik/typechk';

// TODO: Only emit the type checks that are needed

function chkOptional<T>(chk: TC.typecheck<T>): TC.typecheck<T | undefined> {
  return (v: unknown): v is T | undefined => v === undefined || chk(v);
}

export const Keys = Object.freeze({
  AddFileLocation: 'O',
  Albums: '2',
  Artists: '3',
  Backward10s: '[',
  Find: 'F',
  Forward10s: ']',
  NextTrack: 'Right',
  NowPlaying: '1',
  Play: 'P',
  Playlists: '5',
  PreviousTrack: 'Left',
  Repeat: 'T',
  SavePlaylist: 'S',
  Settings: ',',
  Shuffle: 'R',
  Songs: '4',
  ToggleMiniPlayer: '9',
  Tools: 'L',
});
export type Keys = (typeof Keys)[keyof typeof Keys];
export function chkKeys(val: unknown): val is Keys {
  return TC.isString(val) && Object.values(Keys).includes(val as Keys);
}

export const StrId = Object.freeze({
  ChooseFile: 'Choose File...',
  ViewSettings: 'Settings',
});
export type StrId = (typeof StrId)[keyof typeof StrId];
export function chkStrId(val: unknown): val is StrId {
  return TC.isString(val) && Object.values(StrId).includes(val as StrId);
}

export const CurrentView = Object.freeze({
  disabled: -1,
  none: 0,
  recent: 1,
  albums: 2,
  artists: 3,
  songs: 4,
  playlists: 5,
  now_playing: 6,
  settings: 7,
  search: 8,
  tools: 9,
});
export type CurrentView = (typeof CurrentView)[keyof typeof CurrentView];
export function chkCurrentView(val: unknown): val is CurrentView {
  return (
    TC.isNumber(val) && Object.values(CurrentView).includes(val as CurrentView)
  );
}

export const IpcCall = Object.freeze({
  Unknown: 0,
  ReadFromStorage: 1,
  WriteToStorage: 2,
  DeleteFromStorage: 3,
  AsyncData: 4,
  IsDev: 5,
  MenuAction: 6,
  MinimizeWindow: 7,
  MaximizeWindow: 8,
  RestoreWindow: 9,
  CloseWindow: 10,
  ShowOpenDialog: 11,
});
export type IpcCall = (typeof IpcCall)[keyof typeof IpcCall];
export function chkIpcCall(val: unknown): val is IpcCall {
  return TC.isNumber(val) && Object.values(IpcCall).includes(val as IpcCall);
}

export const SocketMsg = Object.freeze({
  Unknown: 0,
  ContentLoaded: 1,
  KeepAlive: 2,
});
export type SocketMsg = (typeof SocketMsg)[keyof typeof SocketMsg];
export function chkSocketMsg(val: unknown): val is SocketMsg {
  return (
    TC.isNumber(val) && Object.values(SocketMsg).includes(val as SocketMsg)
  );
}

export const StorageId = Object.freeze({
  CurrentView: 'currentView',
});
export type StorageId = (typeof StorageId)[keyof typeof StorageId];
export function chkStorageId(val: unknown): val is StorageId {
  return (
    TC.isString(val) && Object.values(StorageId).includes(val as StorageId)
  );
}

export type MimeData = {
  type: string;
  data: string;
};
export const chkMimeData: TC.typecheck<MimeData> = TC.chkObjectOfType(
  {
    type: TC.isString,
    data: TC.isString,
  },
  {},
);

export type FileFilterItem = {
  name: string;
  extensions: string[];
};
export const chkFileFilterItem: TC.typecheck<FileFilterItem> =
  TC.chkObjectOfType(
    {
      name: TC.isString,
      extensions: TC.chkArrayOf(TC.isString),
    },
    {},
  );

export type OpenDialogOptions = {
  folder?: boolean;
  title?: string;
  defaultPath?: string;
  buttonLabel?: string;
  multiSelections?: boolean;
  filters?: FileFilterItem[];
};
export const chkOpenDialogOptions: TC.typecheck<OpenDialogOptions> =
  TC.chkObjectOfType(
    {},
    {
      folder: chkOptional(TC.isBoolean),
      title: chkOptional(TC.isString),
      defaultPath: chkOptional(TC.isString),
      buttonLabel: chkOptional(TC.isString),
      multiSelections: chkOptional(TC.isBoolean),
      filters: chkOptional(TC.chkArrayOf(chkFileFilterItem)),
    },
  );

// End of generated code
