#pragma once
// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from www/Shared/Definitions.ts by running 'crow-idl
// ...' If you need to change this file, edit www/Shared/Definitions.ts and run
// the crow-idl command again. Or, if you need to change the generation process,
// put up a pull-request to https://github.com/kevinfrei/ts-cpp-tooling
// DO NOT EDIT THIS FILE DIRECTLY!!!

// Generated by guidiff v0.1.0

#include <cstdint>
#include <optional>
#include <string_view>
#include <utility>
#include <vector>

#include <crow/json.h>

// TODO: Inline this?
#include "json_pickling.hpp"

namespace Shared {

template <typename T>
constexpr std::optional<T> from_string(const std::string_view& str);

#pragma region string enum Keys

enum class Keys {
  AddFileLocation,
  Albums,
  Artists,
  Backward10s,
  Find,
  Forward10s,
  NextTrack,
  NowPlaying,
  Play,
  Playlists,
  PreviousTrack,
  Repeat,
  SavePlaylist,
  Settings,
  Shuffle,
  Songs,
  ToggleMiniPlayer,
  Tools
};

inline constexpr bool is_valid(Keys _value) {
  switch (_value) {
    case Keys::AddFileLocation:
    case Keys::Albums:
    case Keys::Artists:
    case Keys::Backward10s:
    case Keys::Find:
    case Keys::Forward10s:
    case Keys::NextTrack:
    case Keys::NowPlaying:
    case Keys::Play:
    case Keys::Playlists:
    case Keys::PreviousTrack:
    case Keys::Repeat:
    case Keys::SavePlaylist:
    case Keys::Settings:
    case Keys::Shuffle:
    case Keys::Songs:
    case Keys::ToggleMiniPlayer:
    case Keys::Tools:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(Keys _value) {
  switch (_value) {
    case Keys::AddFileLocation:
      return "O";
    case Keys::Albums:
      return "2";
    case Keys::Artists:
      return "3";
    case Keys::Backward10s:
      return "[";
    case Keys::Find:
      return "F";
    case Keys::Forward10s:
      return "]";
    case Keys::NextTrack:
      return "Right";
    case Keys::NowPlaying:
      return "1";
    case Keys::Play:
      return "P";
    case Keys::Playlists:
      return "5";
    case Keys::PreviousTrack:
      return "Left";
    case Keys::Repeat:
      return "T";
    case Keys::SavePlaylist:
      return "S";
    case Keys::Settings:
      return ",";
    case Keys::Shuffle:
      return "R";
    case Keys::Songs:
      return "4";
    case Keys::ToggleMiniPlayer:
      return "9";
    case Keys::Tools:
      return "L";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<Keys> from_string<Keys>(
    const std::string_view& str) {
  if (str == "O")
    return Keys::AddFileLocation;
  if (str == "2")
    return Keys::Albums;
  if (str == "3")
    return Keys::Artists;
  if (str == "[")
    return Keys::Backward10s;
  if (str == "F")
    return Keys::Find;
  if (str == "]")
    return Keys::Forward10s;
  if (str == "Right")
    return Keys::NextTrack;
  if (str == "1")
    return Keys::NowPlaying;
  if (str == "P")
    return Keys::Play;
  if (str == "5")
    return Keys::Playlists;
  if (str == "Left")
    return Keys::PreviousTrack;
  if (str == "T")
    return Keys::Repeat;
  if (str == "S")
    return Keys::SavePlaylist;
  if (str == ",")
    return Keys::Settings;
  if (str == "R")
    return Keys::Shuffle;
  if (str == "4")
    return Keys::Songs;
  if (str == "9")
    return Keys::ToggleMiniPlayer;
  if (str == "L")
    return Keys::Tools;
  return std::nullopt;
}

#pragma endregion string enum Keys

#pragma region string enum StrId

enum class StrId { ChooseFile, ViewSettings };

inline constexpr bool is_valid(StrId _value) {
  switch (_value) {
    case StrId::ChooseFile:
    case StrId::ViewSettings:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(StrId _value) {
  switch (_value) {
    case StrId::ChooseFile:
      return "Choose File...";
    case StrId::ViewSettings:
      return "Settings";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<StrId> from_string<StrId>(
    const std::string_view& str) {
  if (str == "Choose File...")
    return StrId::ChooseFile;
  if (str == "Settings")
    return StrId::ViewSettings;
  return std::nullopt;
}

#pragma endregion string enum StrId

#pragma region linear enum CurrentView
enum class CurrentView {
  disabled = -1,
  none = 0,
  recent = 1,
  albums = 2,
  artists = 3,
  songs = 4,
  playlists = 5,
  now_playing = 6,
  settings = 7,
  search = 8,
  tools = 9,
};

inline constexpr bool is_valid(CurrentView _value) {
  switch (_value) {
    case CurrentView::disabled:
    case CurrentView::none:
    case CurrentView::recent:
    case CurrentView::albums:
    case CurrentView::artists:
    case CurrentView::songs:
    case CurrentView::playlists:
    case CurrentView::now_playing:
    case CurrentView::settings:
    case CurrentView::search:
    case CurrentView::tools:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(CurrentView _value) {
  switch (_value) {
    case CurrentView::disabled:
      return "disabled";
    case CurrentView::none:
      return "none";
    case CurrentView::recent:
      return "recent";
    case CurrentView::albums:
      return "albums";
    case CurrentView::artists:
      return "artists";
    case CurrentView::songs:
      return "songs";
    case CurrentView::playlists:
      return "playlists";
    case CurrentView::now_playing:
      return "now_playing";
    case CurrentView::settings:
      return "settings";
    case CurrentView::search:
      return "search";
    case CurrentView::tools:
      return "tools";
    default:
      return "<unknown>";
  }
}

#pragma endregion linear enum CurrentView

#pragma region linear enum IpcCall
enum class IpcCall : std::uint8_t {
  Unknown = 0,
  ReadFromStorage = 1,
  WriteToStorage = 2,
  DeleteFromStorage = 3,
  AsyncData = 4,
  IsDev = 5,
  MenuAction = 6,
  MinimizeWindow = 7,
  MaximizeWindow = 8,
  RestoreWindow = 9,
  CloseWindow = 10,
  ShowOpenDialog = 11,
};

inline constexpr bool is_valid(IpcCall _value) {
  switch (_value) {
    case IpcCall::Unknown:
    case IpcCall::ReadFromStorage:
    case IpcCall::WriteToStorage:
    case IpcCall::DeleteFromStorage:
    case IpcCall::AsyncData:
    case IpcCall::IsDev:
    case IpcCall::MenuAction:
    case IpcCall::MinimizeWindow:
    case IpcCall::MaximizeWindow:
    case IpcCall::RestoreWindow:
    case IpcCall::CloseWindow:
    case IpcCall::ShowOpenDialog:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(IpcCall _value) {
  switch (_value) {
    case IpcCall::Unknown:
      return "Unknown";
    case IpcCall::ReadFromStorage:
      return "ReadFromStorage";
    case IpcCall::WriteToStorage:
      return "WriteToStorage";
    case IpcCall::DeleteFromStorage:
      return "DeleteFromStorage";
    case IpcCall::AsyncData:
      return "AsyncData";
    case IpcCall::IsDev:
      return "IsDev";
    case IpcCall::MenuAction:
      return "MenuAction";
    case IpcCall::MinimizeWindow:
      return "MinimizeWindow";
    case IpcCall::MaximizeWindow:
      return "MaximizeWindow";
    case IpcCall::RestoreWindow:
      return "RestoreWindow";
    case IpcCall::CloseWindow:
      return "CloseWindow";
    case IpcCall::ShowOpenDialog:
      return "ShowOpenDialog";
    default:
      return "<unknown>";
  }
}

#pragma endregion linear enum IpcCall

#pragma region numeric enum SocketMsg
enum class SocketMsg : std::uint8_t { Unknown, ContentLoaded, KeepAlive };

inline constexpr bool is_valid(SocketMsg _value) {
  switch (_value) {
    case SocketMsg::Unknown:
    case SocketMsg::ContentLoaded:
    case SocketMsg::KeepAlive:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(SocketMsg _value) {
  switch (_value) {
    case SocketMsg::Unknown:
      return "Unknown";
    case SocketMsg::ContentLoaded:
      return "ContentLoaded";
    case SocketMsg::KeepAlive:
      return "KeepAlive";
    default:
      return "<unknown>";
  }
}
#pragma endregion numeric enum SocketMsg

#pragma region string enum StorageId

enum class StorageId { CurrentView };

inline constexpr bool is_valid(StorageId _value) {
  switch (_value) {
    case StorageId::CurrentView:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(StorageId _value) {
  switch (_value) {
    case StorageId::CurrentView:
      return "currentView";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<StorageId> from_string<StorageId>(
    const std::string_view& str) {
  if (str == "currentView")
    return StorageId::CurrentView;
  return std::nullopt;
}

#pragma endregion string enum StorageId

struct MimeData {
  std::string type;
  std::string data;
};

struct FileFilterItem {
  std::string name;
  std::vector<std::string> extensions;
};

struct OpenDialogOptions {
  std::optional<bool> folder;
  std::optional<std::string> title;
  std::optional<std::string> defaultPath;
  std::optional<std::string> buttonLabel;
  std::optional<bool> multiSelections;
  std::optional<std::vector<FileFilterItem>> filters;
};

} // namespace Shared
#pragma region JSON serialization for string enum Keys
template <>
inline crow::json::wvalue to_json<Shared::Keys>(Shared::Keys _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::Keys> {
  static inline std::optional<Shared::Keys> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::Keys>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum Keys

#pragma region JSON serialization for string enum StrId
template <>
inline crow::json::wvalue to_json<Shared::StrId>(Shared::StrId _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::StrId> {
  static inline std::optional<Shared::StrId> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::StrId>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum StrId

#pragma region JSON serialization for string enum StorageId
template <>
inline crow::json::wvalue to_json<Shared::StorageId>(Shared::StorageId _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::StorageId> {
  static inline std::optional<Shared::StorageId> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::StorageId>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum StorageId

#pragma region JSON serialization for object MimeData
template <>
struct impl_to_json<Shared::MimeData> {
  static inline crow::json::wvalue process(const Shared::MimeData& _value) {
    crow::json::wvalue _res;
    _res["type"] = to_json(_value.type);
    _res["data"] = to_json(_value.data);

    return _res;
  }
};

template <>
inline std::optional<Shared::MimeData> from_json<Shared::MimeData>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::MimeData _res;

  if (!_value.has("type"))
    return std::nullopt;
  auto _type_opt_ = from_json<std::string>(_value["type"]);
  if (!_type_opt_.has_value())
    return std::nullopt;
  _res.type = std::move(*_type_opt_);

  if (!_value.has("data"))
    return std::nullopt;
  auto _data_opt_ = from_json<std::string>(_value["data"]);
  if (!_data_opt_.has_value())
    return std::nullopt;
  _res.data = std::move(*_data_opt_);

  return _res;
}
#pragma endregion JSON serialization for object MimeData

#pragma region JSON serialization for object FileFilterItem
template <>
struct impl_to_json<Shared::FileFilterItem> {
  static inline crow::json::wvalue process(
      const Shared::FileFilterItem& _value) {
    crow::json::wvalue _res;
    _res["name"] = to_json(_value.name);
    _res["extensions"] = to_json(_value.extensions);

    return _res;
  }
};

template <>
inline std::optional<Shared::FileFilterItem> from_json<Shared::FileFilterItem>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::FileFilterItem _res;

  if (!_value.has("name"))
    return std::nullopt;
  auto _name_opt_ = from_json<std::string>(_value["name"]);
  if (!_name_opt_.has_value())
    return std::nullopt;
  _res.name = std::move(*_name_opt_);

  if (!_value.has("extensions"))
    return std::nullopt;
  auto _extensions_opt_ =
      from_json<std::vector<std::string>>(_value["extensions"]);
  if (!_extensions_opt_.has_value())
    return std::nullopt;
  _res.extensions = std::move(*_extensions_opt_);

  return _res;
}
#pragma endregion JSON serialization for object FileFilterItem

#pragma region JSON serialization for object OpenDialogOptions
template <>
struct impl_to_json<Shared::OpenDialogOptions> {
  static inline crow::json::wvalue process(
      const Shared::OpenDialogOptions& _value) {
    crow::json::wvalue _res;

    if (_value.folder) {
      _res["folder"] = to_json(*_value.folder);
    }
    if (_value.title) {
      _res["title"] = to_json(*_value.title);
    }
    if (_value.defaultPath) {
      _res["defaultPath"] = to_json(*_value.defaultPath);
    }
    if (_value.buttonLabel) {
      _res["buttonLabel"] = to_json(*_value.buttonLabel);
    }
    if (_value.multiSelections) {
      _res["multiSelections"] = to_json(*_value.multiSelections);
    }
    if (_value.filters) {
      _res["filters"] = to_json(*_value.filters);
    }
    return _res;
  }
};

template <>
inline std::optional<Shared::OpenDialogOptions>
from_json<Shared::OpenDialogOptions>(const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::OpenDialogOptions _res;

  if (_value.has("folder")) {
    auto _folder_opt_ = from_json<bool>(_value["folder"]);
    if (!_folder_opt_.has_value())
      return std::nullopt;
    _res.folder = std::move(*_folder_opt_);
  } else {
    _res.folder = std::nullopt;
  }

  if (_value.has("title")) {
    auto _title_opt_ = from_json<std::string>(_value["title"]);
    if (!_title_opt_.has_value())
      return std::nullopt;
    _res.title = std::move(*_title_opt_);
  } else {
    _res.title = std::nullopt;
  }

  if (_value.has("defaultPath")) {
    auto _defaultPath_opt_ = from_json<std::string>(_value["defaultPath"]);
    if (!_defaultPath_opt_.has_value())
      return std::nullopt;
    _res.defaultPath = std::move(*_defaultPath_opt_);
  } else {
    _res.defaultPath = std::nullopt;
  }

  if (_value.has("buttonLabel")) {
    auto _buttonLabel_opt_ = from_json<std::string>(_value["buttonLabel"]);
    if (!_buttonLabel_opt_.has_value())
      return std::nullopt;
    _res.buttonLabel = std::move(*_buttonLabel_opt_);
  } else {
    _res.buttonLabel = std::nullopt;
  }

  if (_value.has("multiSelections")) {
    auto _multiSelections_opt_ = from_json<bool>(_value["multiSelections"]);
    if (!_multiSelections_opt_.has_value())
      return std::nullopt;
    _res.multiSelections = std::move(*_multiSelections_opt_);
  } else {
    _res.multiSelections = std::nullopt;
  }

  if (_value.has("filters")) {
    auto _filters_opt_ =
        from_json<std::vector<Shared::FileFilterItem>>(_value["filters"]);
    if (!_filters_opt_.has_value())
      return std::nullopt;
    _res.filters = std::move(*_filters_opt_);
  } else {
    _res.filters = std::nullopt;
  }
  return _res;
}
#pragma endregion JSON serialization for object OpenDialogOptions
